name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

# Example:
# https://levelup.gitconnected.com/utilizing-github-actions-to-build-and-test-on-multiple-platforms-a7fe3aa6ce2a
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cmake-options: -DUBSAN=ON -DASAN=ON
            target: Linux
          - os: windows-latest
            cmake-options:
            target: Windows
          - os: macos-latest
            cmake-options: -DUBSAN=ON -DASAN=ON
            target: macOS

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.cmake-options}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Compare Unix results with pre-recorded outputs
      if: ${{ matrix.os != 'windows-latest' }}
      working-directory: ${{github.workspace}}/build
      run: |
        ./tracer ../cat-and-mouse.if ../cat-and-mouse-1.xtr > cat-and-mouse-1.txt
        diff ../cat-and-mouse-1.txt cat-and-mouse-1.txt
        ./tracer ../cat-and-mouse.if ../cat-and-mouse-1.xtr > cat-and-mouse-cheese.txt
        diff ../cat-and-mouse-cheese.txt cat-and-mouse-cheese.txt

    - name: Compare Windows results with pre-recorded outputs
      if: ${{ matrix.os == 'windows-latest' }}
      working-directory: ${{github.workspace}}/build
      run: |
        ${{env.BUILD_TYPE}}\tracer.exe ..\cat-and-mouse.if ..\cat-and-mouse-1.xtr > cat-and-mouse-1.txt
        fc.exe /L ..\cat-and-mouse-1.txt cat-and-mouse-1.txt
        ${{env.BUILD_TYPE}}\tracer.exe ..\cat-and-mouse.if ..\cat-and-mouse-1.xtr > cat-and-mouse-cheese.txt
        fc.exe /L ..\cat-and-mouse-cheese.txt cat-and-mouse-cheese.txt
